
package views;

/**
 *
 * @author gasler
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(600, 540);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contentTablero = new javax.swing.JPanel();
        tablero = new javax.swing.JPanel();
        A1 = new javax.swing.JPanel();
        B1 = new javax.swing.JPanel();
        C1 = new javax.swing.JPanel();
        D1 = new javax.swing.JPanel();
        E1 = new javax.swing.JPanel();
        F1 = new javax.swing.JPanel();
        G1 = new javax.swing.JPanel();
        H1 = new javax.swing.JPanel();
        A2 = new javax.swing.JPanel();
        B2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        C2 = new javax.swing.JPanel();
        D2 = new javax.swing.JPanel();
        E2 = new javax.swing.JPanel();
        F2 = new javax.swing.JPanel();
        G2 = new javax.swing.JPanel();
        H2 = new javax.swing.JPanel();
        A3 = new javax.swing.JPanel();
        B3 = new javax.swing.JPanel();
        C3 = new javax.swing.JPanel();
        D3 = new javax.swing.JPanel();
        E3 = new javax.swing.JPanel();
        F3 = new javax.swing.JPanel();
        G3 = new javax.swing.JPanel();
        H3 = new javax.swing.JPanel();
        A4 = new javax.swing.JPanel();
        B4 = new javax.swing.JPanel();
        C4 = new javax.swing.JPanel();
        D4 = new javax.swing.JPanel();
        E4 = new javax.swing.JPanel();
        F4 = new javax.swing.JPanel();
        G4 = new javax.swing.JPanel();
        H4 = new javax.swing.JPanel();
        A5 = new javax.swing.JPanel();
        B5 = new javax.swing.JPanel();
        C5 = new javax.swing.JPanel();
        D5 = new javax.swing.JPanel();
        E5 = new javax.swing.JPanel();
        F5 = new javax.swing.JPanel();
        G5 = new javax.swing.JPanel();
        H5 = new javax.swing.JPanel();
        A6 = new javax.swing.JPanel();
        B6 = new javax.swing.JPanel();
        C6 = new javax.swing.JPanel();
        D6 = new javax.swing.JPanel();
        E6 = new javax.swing.JPanel();
        F6 = new javax.swing.JPanel();
        G6 = new javax.swing.JPanel();
        H6 = new javax.swing.JPanel();
        A7 = new javax.swing.JPanel();
        B7 = new javax.swing.JPanel();
        C7 = new javax.swing.JPanel();
        D7 = new javax.swing.JPanel();
        E7 = new javax.swing.JPanel();
        F7 = new javax.swing.JPanel();
        G7 = new javax.swing.JPanel();
        H7 = new javax.swing.JPanel();
        A8 = new javax.swing.JPanel();
        B8 = new javax.swing.JPanel();
        C8 = new javax.swing.JPanel();
        D8 = new javax.swing.JPanel();
        E8 = new javax.swing.JPanel();
        F8 = new javax.swing.JPanel();
        G8 = new javax.swing.JPanel();
        H8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 239, 192));
        jPanel1.setLayout(null);

        contentTablero.setBackground(new java.awt.Color(0, 0, 0));
        contentTablero.setLayout(null);

        tablero.setBackground(new java.awt.Color(255, 255, 255));
        tablero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroMouseClicked(evt);
            }
        });
        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        B1.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        C1.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        D1.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 50));

        E1.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 50, 50));

        F1.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

        G1.setBackground(new java.awt.Color(255, 255, 255));
        G1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablero.add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 50, 50));

        H1.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 50, 50));

        A2.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 50));

        B2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peonBlanco.png"))); // NOI18N
        jLabel19.setText("1");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        B2.add(jLabel19);

        tablero.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        C2.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 50));

        D2.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 50));

        E2.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, 50));

        F2.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 50));

        G2.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 50));

        H2.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 50));

        A3.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 50));

        B3.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 50));

        C3.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        D3.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 50));

        E3.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 50, 50));

        F3.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 50, 50));

        G3.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 50, 50));

        H3.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 50, 50));

        A4.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 50, 50));

        B4.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, 50));

        C4.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 50));

        D4.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, 50));

        E4.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 50));

        F4.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 50, 50));

        G4.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 50, 50));

        H4.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 50, 50));

        A5.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 50));

        B5.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 50));

        C5.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 50, 50));

        D5.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 50));

        E5.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, 50));

        F5.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, 50));

        G5.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 50, 50));

        H5.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 50));

        A6.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 50, 50));

        B6.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 50, 50));

        C6.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, 50));

        D6.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 50));

        E6.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 50, 50));

        F6.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, 50));

        G6.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 50, 50));

        H6.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 50, 50));

        A7.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 50));

        B7.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 50, 50));

        C7.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 50, 50));

        D7.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 50, 50));

        E7.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 50, 50));

        F7.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 50, 50));

        G7.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 50, 50));

        H7.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 50, 50));

        A8.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 50, 50));

        B8.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 50, 50));

        C8.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 50, 50));

        D8.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 50));

        E8.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 50, 50));

        F8.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 50, 50));

        G8.setBackground(new java.awt.Color(0, 0, 0));
        tablero.add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 50, 50));

        H8.setBackground(new java.awt.Color(255, 255, 255));
        tablero.add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 50, 50));

        contentTablero.add(tablero);
        tablero.setBounds(25, 25, 400, 400);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     A              B              C              D              E               F              G              H");
        contentTablero.add(jLabel1);
        jLabel1.setBounds(30, 430, 390, 14);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("8");
        contentTablero.add(jLabel2);
        jLabel2.setBounds(10, 390, 10, 14);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1");
        contentTablero.add(jLabel3);
        jLabel3.setBounds(10, 40, 10, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2");
        contentTablero.add(jLabel4);
        jLabel4.setBounds(10, 90, 10, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3");
        contentTablero.add(jLabel5);
        jLabel5.setBounds(10, 140, 10, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4");
        contentTablero.add(jLabel6);
        jLabel6.setBounds(10, 190, 10, 14);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5");
        contentTablero.add(jLabel7);
        jLabel7.setBounds(10, 240, 10, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6");
        contentTablero.add(jLabel8);
        jLabel8.setBounds(10, 290, 10, 14);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("7");
        contentTablero.add(jLabel9);
        jLabel9.setBounds(10, 340, 10, 14);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("3");
        contentTablero.add(jLabel10);
        jLabel10.setBounds(430, 140, 10, 14);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2");
        contentTablero.add(jLabel11);
        jLabel11.setBounds(430, 90, 10, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("1");
        contentTablero.add(jLabel12);
        jLabel12.setBounds(430, 40, 10, 14);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("4");
        contentTablero.add(jLabel13);
        jLabel13.setBounds(430, 190, 10, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("5");
        contentTablero.add(jLabel14);
        jLabel14.setBounds(430, 240, 10, 14);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("6");
        contentTablero.add(jLabel15);
        jLabel15.setBounds(430, 290, 10, 14);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("7");
        contentTablero.add(jLabel16);
        jLabel16.setBounds(430, 340, 10, 14);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("8");
        contentTablero.add(jLabel17);
        jLabel17.setBounds(430, 390, 10, 14);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("     A              B              C              D              E               F              G              H");
        contentTablero.add(jLabel18);
        jLabel18.setBounds(30, 10, 390, 14);

        jPanel1.add(contentTablero);
        contentTablero.setBounds(10, 40, 450, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroMouseClicked
        System.out.println(evt.getX());
    }//GEN-LAST:event_tableroMouseClicked
//Object arg
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        System.out.println(evt.getPoint());
    }//GEN-LAST:event_jLabel19MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A1;
    private javax.swing.JPanel A2;
    private javax.swing.JPanel A3;
    private javax.swing.JPanel A4;
    private javax.swing.JPanel A5;
    private javax.swing.JPanel A6;
    private javax.swing.JPanel A7;
    private javax.swing.JPanel A8;
    private javax.swing.JPanel B1;
    private javax.swing.JPanel B2;
    private javax.swing.JPanel B3;
    private javax.swing.JPanel B4;
    private javax.swing.JPanel B5;
    private javax.swing.JPanel B6;
    private javax.swing.JPanel B7;
    private javax.swing.JPanel B8;
    private javax.swing.JPanel C1;
    private javax.swing.JPanel C2;
    private javax.swing.JPanel C3;
    private javax.swing.JPanel C4;
    private javax.swing.JPanel C5;
    private javax.swing.JPanel C6;
    private javax.swing.JPanel C7;
    private javax.swing.JPanel C8;
    private javax.swing.JPanel D1;
    private javax.swing.JPanel D2;
    private javax.swing.JPanel D3;
    private javax.swing.JPanel D4;
    private javax.swing.JPanel D5;
    private javax.swing.JPanel D6;
    private javax.swing.JPanel D7;
    private javax.swing.JPanel D8;
    private javax.swing.JPanel E1;
    private javax.swing.JPanel E2;
    private javax.swing.JPanel E3;
    private javax.swing.JPanel E4;
    private javax.swing.JPanel E5;
    private javax.swing.JPanel E6;
    private javax.swing.JPanel E7;
    private javax.swing.JPanel E8;
    private javax.swing.JPanel F1;
    private javax.swing.JPanel F2;
    private javax.swing.JPanel F3;
    private javax.swing.JPanel F4;
    private javax.swing.JPanel F5;
    private javax.swing.JPanel F6;
    private javax.swing.JPanel F7;
    private javax.swing.JPanel F8;
    private javax.swing.JPanel G1;
    private javax.swing.JPanel G2;
    private javax.swing.JPanel G3;
    private javax.swing.JPanel G4;
    private javax.swing.JPanel G5;
    private javax.swing.JPanel G6;
    private javax.swing.JPanel G7;
    private javax.swing.JPanel G8;
    private javax.swing.JPanel H1;
    private javax.swing.JPanel H2;
    private javax.swing.JPanel H3;
    private javax.swing.JPanel H4;
    private javax.swing.JPanel H5;
    private javax.swing.JPanel H6;
    private javax.swing.JPanel H7;
    private javax.swing.JPanel H8;
    private javax.swing.JPanel contentTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
